// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARTvQL7BUN91gA3ukDI4k2jEuH5wasvow',
    appId: '1:147183549958:web:720025339db1c4a47b4d87',
    messagingSenderId: '147183549958',
    projectId: 'news-app-a5f00',
    authDomain: 'news-app-a5f00.firebaseapp.com',
    storageBucket: 'news-app-a5f00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg7Mm71KYj4VgKBlQy-udDjNQUK8JJBxo',
    appId: '1:147183549958:android:9b12540f515ecdef7b4d87',
    messagingSenderId: '147183549958',
    projectId: 'news-app-a5f00',
    storageBucket: 'news-app-a5f00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjAV6zoL08Ay4o4nGJiABKV-POV6L5zD8',
    appId: '1:147183549958:ios:fcb70e2f159b675c7b4d87',
    messagingSenderId: '147183549958',
    projectId: 'news-app-a5f00',
    storageBucket: 'news-app-a5f00.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );
}
